import type { PentagonSignal, PsychologySignal, SocialSignal } from './types';

function isoMinutesAgo(minutes: number) {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

export function getDemoSignals() {
  const pentagon: PentagonSignal[] = [
    {
      id: 'pizza-index',
      slug: 'pizza-index',
      domain: 'pentagon',
      indexType: 'pizza',
      title: 'Pizza Index',
      subtitle: 'Late-night chain order pressure',
      summary:
        'Late-night pizza orders remain above the recent baseline across monitored districts, pointing to broader after-hours activity staying firm.',
      score: 74,
      classification: 'Elevated activity',
      change: 6.4,
      updatedAt: isoMinutesAgo(22),
      confidenceBand: 'high',
      freshnessNote: 'Updated inside the target hourly cadence.',
      uncertaintyNote: 'Coverage is aggregate-first, so district differences can be hidden inside the roll-up.',
      detailPath: '/pentagon/pizza-index',
      metrics: [
        { label: 'Orders vs baseline', value: '+18%', tone: 'warm' },
        { label: 'Late-night mix', value: '67%', tone: 'warm' },
        { label: 'Coverage', value: '12 districts' },
      ],
      drivers: [
        'Weekend order volume accelerated faster than the trailing two-week baseline.',
        'Late-night demand contributed a larger share of total activity than usual.',
        'The footprint broadened without a single district dominating the read.',
      ],
      cadenceHours: 1,
      sampleSize: 428,
      coverageLabel: '12 monitored districts',
    },
    {
      id: 'gay-bar-index',
      slug: 'gay-bar-index',
      domain: 'pentagon',
      indexType: 'gay-bar',
      title: 'Gay Bar Index',
      subtitle: 'Aggregate nightlife attendance read',
      summary:
        'Attendance remains firm but less stretched than the pizza read, suggesting steady nightlife participation without a broad breakout.',
      score: 61,
      classification: 'Firm participation',
      change: 2.1,
      updatedAt: isoMinutesAgo(69),
      confidenceBand: 'medium',
      freshnessNote: 'Near the upper edge of the hourly cadence.',
      uncertaintyNote: 'The index suppresses venue-level granularity by design, so micro hotspots do not surface here.',
      detailPath: '/pentagon/gay-bar-index',
      metrics: [
        { label: 'Attendance vs baseline', value: '+9%', tone: 'warm' },
        { label: 'Queue intensity', value: 'Stable', tone: 'neutral' },
        { label: 'Coverage', value: '8 districts' },
      ],
      drivers: [
        'Attendance held above the short-term baseline across most monitored areas.',
        'Queue pressure stabilized rather than accelerating into the close.',
        'The read stayed broad enough to avoid looking like a single-neighborhood spike.',
      ],
      cadenceHours: 1,
      sampleSize: 193,
      coverageLabel: '8 monitored districts',
    },
  ];

  const psychology: PsychologySignal[] = [
    {
      id: 'fear-greed',
      slug: 'fear-greed',
      domain: 'psychology',
      indicatorType: 'fear-greed',
      title: 'Fear & Greed Composite',
      subtitle: 'Mood across structured sentiment inputs',
      summary:
        'Risk appetite is rebuilding, but the reading is still best described as constructive rather than euphoric.',
      score: 63,
      classification: 'Risk appetite rebuilding',
      change: 7.2,
      updatedAt: isoMinutesAgo(18),
      confidenceBand: 'high',
      freshnessNote: 'Fresh within the latest hourly batch.',
      uncertaintyNote: 'Composite moves can smooth over conflicting sub-signals, so the component read matters.',
      detailPath: '/psychology/fear-greed',
      metrics: [
        { label: 'Volatility tone', value: 'Cooling', tone: 'cool' },
        { label: 'Breadth support', value: 'Improving', tone: 'warm' },
        { label: 'Flow appetite', value: 'Positive', tone: 'warm' },
      ],
      drivers: [
        'Volatility-sensitive inputs eased from the prior hour.',
        'Participation breadth widened enough to support the composite.',
        'Flow indicators leaned constructive without crossing into an extreme read.',
      ],
      cadenceHours: 1,
    },
    {
      id: 'positioning-heat',
      slug: 'positioning-heat',
      domain: 'psychology',
      indicatorType: 'positioning-heat',
      title: 'Positioning Heat',
      subtitle: 'Crowding and one-sidedness',
      summary:
        'Positioning looks balanced overall, with neither defensive unwinds nor aggressive crowding dominating the snapshot.',
      score: 48,
      classification: 'Balanced positioning',
      change: -1.4,
      updatedAt: isoMinutesAgo(54),
      confidenceBand: 'medium',
      freshnessNote: 'Still inside the target update window.',
      uncertaintyNote: 'Crowding reads can reverse quickly when liquidity thins, so this should be read as a current-state snapshot.',
      detailPath: '/psychology/positioning-heat',
      metrics: [
        { label: 'Crowding', value: 'Contained', tone: 'cool' },
        { label: 'Dealer stress', value: 'Muted', tone: 'cool' },
        { label: 'One-sidedness', value: 'Low', tone: 'neutral' },
      ],
      drivers: [
        'Crowding metrics faded modestly from the prior hour.',
        'Dealer-stress proxies remained contained across the structured feed.',
        'No single subcomponent moved enough to tilt the aggregate reading sharply.',
      ],
      cadenceHours: 1,
    },
    {
      id: 'breadth-stress',
      slug: 'breadth-stress',
      domain: 'psychology',
      indicatorType: 'breadth-stress',
      title: 'Breadth Stress',
      subtitle: 'How broad participation feels beneath the tape',
      summary:
        'Participation remains guarded, with fewer supporting components carrying the latest move than a healthier backdrop would show.',
      score: 32,
      classification: 'Guarded participation',
      change: -5.1,
      updatedAt: isoMinutesAgo(101),
      confidenceBand: 'limited',
      freshnessNote: 'This reading is older than the normal hourly cadence.',
      uncertaintyNote: 'Because this snapshot is stale, treat the classification as lagged until the next refresh lands.',
      detailPath: '/psychology/breadth-stress',
      metrics: [
        { label: 'Participation', value: 'Thin', tone: 'cool' },
        { label: 'Leadership', value: 'Narrow', tone: 'cool' },
        { label: 'Recovery speed', value: 'Slow', tone: 'neutral' },
      ],
      drivers: [
        'Participation stayed narrow across the latest published components.',
        'Leadership did not broaden enough to offset the weaker breadth inputs.',
        'The stale timestamp adds uncertainty until a new batch confirms or reverses the move.',
      ],
      cadenceHours: 1,
    },
  ];

  const social: SocialSignal[] = [
    {
      id: 'consumer-chatter',
      slug: 'consumer-chatter',
      domain: 'social',
      title: 'Consumer Chatter Re-accelerating',
      subtitle: 'Reviewed aggregate social item',
      summary:
        'Approved consumer-facing posts and comments picked up meaningfully, with volume rising faster than the recent baseline in the last hour.',
      score: 68,
      classification: 'Conversation building',
      change: 4.8,
      updatedAt: isoMinutesAgo(15),
      confidenceBand: 'high',
      freshnessNote: 'Published from the latest review window.',
      uncertaintyNote: 'Conversation volume can jump around event-driven posts, so context from the source mix still matters.',
      detailPath: '/sns/consumer-chatter',
      metrics: [
        { label: 'Reviewed sources', value: '14', tone: 'warm' },
        { label: 'Comment pace', value: '+21%', tone: 'warm' },
        { label: 'Signal mix', value: 'Broad' },
      ],
      drivers: [
        'Approved items showed stronger than normal consumer engagement.',
        'The source mix stayed broad across multiple channels rather than a single bursty thread.',
        'Follow-up comments remained additive rather than reversing the initial tone.',
      ],
      cadenceHours: 1,
      sourceCount: 14,
      categories: ['Consumer', 'Behavior'],
      sources: ['X', 'Reddit', 'Community'],
      approvalNote: 'Only items that passed the approval gate are surfaced in the user-facing feed.',
    },
    {
      id: 'macro-anxiety',
      slug: 'macro-anxiety',
      domain: 'social',
      title: 'Macro Anxiety Cooling',
      subtitle: 'Reviewed aggregate social item',
      summary:
        'Macro-related worry is still present, but the approved feed shows fewer concentrated spikes than earlier in the session.',
      score: 42,
      classification: 'Stress easing',
      change: -3.3,
      updatedAt: isoMinutesAgo(43),
      confidenceBand: 'medium',
      freshnessNote: 'Refreshed within the last hour.',
      uncertaintyNote: 'Macro chatter can re-accelerate quickly on new headlines, so treat this as a current-state read.',
      detailPath: '/sns/macro-anxiety',
      metrics: [
        { label: 'Reviewed sources', value: '10' },
        { label: 'Spike intensity', value: '-12%', tone: 'cool' },
        { label: 'Topic spread', value: 'Contained', tone: 'cool' },
      ],
      drivers: [
        'Fewer approved posts clustered around the same concern category.',
        'The intensity of macro-stress language faded versus the prior hour.',
        'Topic spread stayed contained enough to prevent a larger aggregate jump.',
      ],
      cadenceHours: 1,
      sourceCount: 10,
      categories: ['Macro', 'Flows'],
      sources: ['X', 'Telegram', 'Community'],
      approvalNote: 'This screen surfaces reviewed aggregate items only. Moderation and ingestion controls remain outside the user app.',
    },
    {
      id: 'behavior-rotation',
      slug: 'behavior-rotation',
      domain: 'social',
      title: 'Behavior Signals Rotating',
      subtitle: 'Reviewed aggregate social item',
      summary:
        'Behavioral chatter is rotating rather than collapsing, with newer themes replacing older ones fast enough to keep the feed active.',
      score: 57,
      classification: 'Rotation underway',
      change: 1.7,
      updatedAt: isoMinutesAgo(82),
      confidenceBand: 'medium',
      freshnessNote: 'Near the edge of the hourly rhythm.',
      uncertaintyNote: 'Because the conversation is rotating, the aggregate label can look steadier than the underlying theme shifts.',
      detailPath: '/sns/behavior-rotation',
      metrics: [
        { label: 'Reviewed sources', value: '9' },
        { label: 'Theme churn', value: 'High', tone: 'warm' },
        { label: 'Overlap', value: 'Low', tone: 'cool' },
      ],
      drivers: [
        'New topics replaced older ones quickly enough to keep the feed active.',
        'Cross-source overlap remained low, which capped aggregate certainty.',
        'The classification reflects continuity in activity, not a single dominant theme.',
      ],
      cadenceHours: 1,
      sourceCount: 9,
      categories: ['Behavior', 'Flows'],
      sources: ['Reddit', 'Community', 'Blogs'],
      approvalNote: 'Only approval-gated items appear here, so a quiet state can simply mean nothing cleared the publication bar.',
    },
  ];

  return {
    pentagon,
    psychology,
    social,
  };
}
