import type { PentagonSignal, PsychologySignal, SocialSignal } from './types';

function isoMinutesAgo(minutes: number) {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

export function getDemoSignals() {
  const pentagon: PentagonSignal[] = [
    {
      id: 'pizza-index',
      slug: 'pizza-index',
      domain: 'pentagon',
      indexType: 'pizza',
      title: '피자 지수',
      subtitle: '심야 주문 압력',
      summary:
        '모니터링 구역 전반에서 심야 피자 주문이 최근 기준선을 웃돌며, 시간 외 활동이 견조하게 유지되고 있습니다.',
      score: 74,
      classification: '활동 강세',
      change: 6.4,
      updatedAt: isoMinutesAgo(22),
      confidenceBand: 'high',
      freshnessNote: '목표한 시간 단위 갱신 주기 안에서 업데이트됐습니다.',
      uncertaintyNote: '집계 중심 지표라서 지역별 편차가 평균값 안에 가려질 수 있습니다.',
      detailPath: '/pentagon/pizza-index',
      metrics: [
        { label: '기준 대비 주문', value: '+18%', tone: 'warm' },
        { label: '심야 비중', value: '67%', tone: 'warm' },
        { label: '커버리지', value: '12개 구역' },
      ],
      drivers: [
        '주말 주문량이 최근 2주 기준선보다 빠르게 늘었습니다.',
        '심야 수요 비중이 평소보다 높게 반영됐습니다.',
        '특정 한 구역이 아니라 전반적인 확산 형태로 나타났습니다.',
      ],
      cadenceHours: 1,
      sampleSize: 428,
      coverageLabel: '12개 모니터링 구역',
    },
    {
      id: 'gay-bar-index',
      slug: 'gay-bar-index',
      domain: 'pentagon',
      indexType: 'gay-bar',
      title: '바 지수',
      subtitle: '야간 유입 집계',
      summary:
        '유입은 견조하지만 피자 지수만큼 과열되지는 않아, 야간 활동이 안정적으로 이어지는 흐름으로 보입니다.',
      score: 61,
      classification: '안정적 유입',
      change: 2.1,
      updatedAt: isoMinutesAgo(69),
      confidenceBand: 'medium',
      freshnessNote: '시간 단위 갱신 주기 상단에 가까운 시점입니다.',
      uncertaintyNote: '개별 장소 수준 세부 정보는 제외되므로, 작은 지역 급등은 여기서 바로 드러나지 않습니다.',
      detailPath: '/pentagon/gay-bar-index',
      metrics: [
        { label: '기준 대비 유입', value: '+9%', tone: 'warm' },
        { label: '대기 강도', value: '안정', tone: 'neutral' },
        { label: '커버리지', value: '8개 구역' },
      ],
      drivers: [
        '대부분의 모니터링 구역에서 유입이 단기 기준선을 웃돌았습니다.',
        '마감으로 갈수록 대기 압력이 급증하지 않고 안정적으로 유지됐습니다.',
        '특정 한 지역 급등이 아닌 넓은 범위의 흐름으로 나타났습니다.',
      ],
      cadenceHours: 1,
      sampleSize: 193,
      coverageLabel: '8개 모니터링 구역',
    },
  ];

  const psychology: PsychologySignal[] = [
    {
      id: 'fear-greed',
      slug: 'fear-greed',
      domain: 'psychology',
      indicatorType: 'fear-greed',
      title: '공포·탐욕 지수',
      subtitle: '구조화된 심리 데이터 종합',
      summary:
        '위험 선호가 다시 살아나고 있지만, 아직 과열보다는 개선 흐름에 가깝습니다.',
      score: 63,
      classification: '위험 선호 회복',
      change: 7.2,
      updatedAt: isoMinutesAgo(18),
      confidenceBand: 'high',
      freshnessNote: '가장 최근 시간 단위 배치 안에서 갱신됐습니다.',
      uncertaintyNote: '종합 지표 특성상 상충하는 세부 신호가 완만하게 보일 수 있습니다.',
      detailPath: '/psychology/fear-greed',
      metrics: [
        { label: '변동성 톤', value: '완화', tone: 'cool' },
        { label: '시장 폭 지지', value: '개선', tone: 'warm' },
        { label: '자금 선호', value: '긍정', tone: 'warm' },
      ],
      drivers: [
        '변동성 민감 지표가 이전 시간보다 완화됐습니다.',
        '참여 폭이 넓어지며 종합 지수를 지지했습니다.',
        '자금 흐름 지표가 과열 전 단계의 긍정 구간으로 기울었습니다.',
      ],
      cadenceHours: 1,
    },
    {
      id: 'positioning-heat',
      slug: 'positioning-heat',
      domain: 'psychology',
      indicatorType: 'positioning-heat',
      title: '포지셔닝 열기',
      subtitle: '쏠림과 혼잡도',
      summary:
        '전반적인 포지셔닝은 균형적이며, 방어적 해소나 공격적 쏠림이 두드러지지 않습니다.',
      score: 48,
      classification: '균형 구간',
      change: -1.4,
      updatedAt: isoMinutesAgo(54),
      confidenceBand: 'medium',
      freshnessNote: '목표 갱신 구간 안에 있습니다.',
      uncertaintyNote: '유동성이 얇아지면 쏠림 지표는 빠르게 반전될 수 있습니다.',
      detailPath: '/psychology/positioning-heat',
      metrics: [
        { label: '쏠림', value: '제한적', tone: 'cool' },
        { label: '딜러 스트레스', value: '낮음', tone: 'cool' },
        { label: '편향도', value: '낮음', tone: 'neutral' },
      ],
      drivers: [
        '쏠림 지표가 직전 시간보다 소폭 완화됐습니다.',
        '딜러 스트레스 관련 지표가 전반적으로 안정적이었습니다.',
        '특정 세부 항목 하나가 전체 방향을 바꿀 정도로 움직이지 않았습니다.',
      ],
      cadenceHours: 1,
    },
    {
      id: 'breadth-stress',
      slug: 'breadth-stress',
      domain: 'psychology',
      indicatorType: 'breadth-stress',
      title: '시장 폭 스트레스',
      subtitle: '시장 내부 참여 폭',
      summary:
        '참여 폭이 여전히 제한적이어서, 건강한 장세에 비해 상승을 지지하는 구성 요소가 적습니다.',
      score: 32,
      classification: '제한적 참여',
      change: -5.1,
      updatedAt: isoMinutesAgo(101),
      confidenceBand: 'limited',
      freshnessNote: '일반적인 시간 단위 갱신보다 오래된 값입니다.',
      uncertaintyNote: '이 스냅샷은 지연된 값이므로 다음 갱신 전까지는 시차를 감안해야 합니다.',
      detailPath: '/psychology/breadth-stress',
      metrics: [
        { label: '참여 폭', value: '좁음', tone: 'cool' },
        { label: '주도주 폭', value: '제한적', tone: 'cool' },
        { label: '회복 속도', value: '느림', tone: 'neutral' },
      ],
      drivers: [
        '최근 공개된 구성 지표 전반에서 참여 폭이 좁게 유지됐습니다.',
        '주도 구간이 넓어지지 않아 약한 시장 폭을 상쇄하지 못했습니다.',
        '지연된 시점 값이라 다음 배치 전까지 불확실성이 남아 있습니다.',
      ],
      cadenceHours: 1,
    },
  ];

  const social: SocialSignal[] = [
    {
      id: 'consumer-chatter',
      slug: 'consumer-chatter',
      domain: 'social',
      title: '소비 대화 재가속',
      subtitle: '검토된 SNS 집계 항목',
      summary:
        '승인된 소비 관련 게시물과 댓글이 다시 늘어나며 최근 기준선보다 빠른 증가 흐름을 보였습니다.',
      score: 68,
      classification: '대화 확산',
      change: 4.8,
      updatedAt: isoMinutesAgo(15),
      confidenceBand: 'high',
      freshnessNote: '가장 최근 검토 구간에서 공개됐습니다.',
      uncertaintyNote: '이벤트성 게시물에 따라 대화량이 급증할 수 있어 출처 구성이 중요합니다.',
      detailPath: '/sns/consumer-chatter',
      metrics: [
        { label: '검토 출처 수', value: '14', tone: 'warm' },
        { label: '댓글 증가율', value: '+21%', tone: 'warm' },
        { label: '시그널 범위', value: '넓음' },
      ],
      drivers: [
        '승인된 항목에서 소비자 참여가 평소보다 강하게 나타났습니다.',
        '단일 채널 급등이 아니라 여러 채널에 걸쳐 넓게 분산됐습니다.',
        '후속 댓글 흐름도 초기 톤을 뒤집기보다 강화하는 쪽이었습니다.',
      ],
      cadenceHours: 1,
      sourceCount: 14,
      categories: ['소비', '행동'],
      sources: ['X', 'Reddit', '커뮤니티'],
      approvalNote: '승인 절차를 통과한 항목만 사용자용 피드에 노출됩니다.',
    },
    {
      id: 'macro-anxiety',
      slug: 'macro-anxiety',
      domain: 'social',
      title: '거시 불안 완화',
      subtitle: '검토된 SNS 집계 항목',
      summary:
        '거시 불안은 남아 있지만, 승인된 피드 기준으로는 초반보다 집중 급등이 줄어든 상태입니다.',
      score: 42,
      classification: '불안 완화',
      change: -3.3,
      updatedAt: isoMinutesAgo(43),
      confidenceBand: 'medium',
      freshnessNote: '최근 1시간 안에 갱신됐습니다.',
      uncertaintyNote: '새 헤드라인이 나오면 거시 불안 대화는 빠르게 다시 늘 수 있습니다.',
      detailPath: '/sns/macro-anxiety',
      metrics: [
        { label: '검토 출처 수', value: '10' },
        { label: '급등 강도', value: '-12%', tone: 'cool' },
        { label: '주제 확산', value: '제한적', tone: 'cool' },
      ],
      drivers: [
        '같은 우려 주제에 집중된 승인 게시물이 줄었습니다.',
        '거시 스트레스 표현 강도가 이전 시간보다 완화됐습니다.',
        '주제 확산이 제한적으로 유지되며 전체 급등을 막았습니다.',
      ],
      cadenceHours: 1,
      sourceCount: 10,
      categories: ['거시', '자금 흐름'],
      sources: ['X', 'Telegram', '커뮤니티'],
      approvalNote: '이 화면에는 검토된 집계 항목만 노출되며, 운영 도구는 사용자 앱 밖에 있습니다.',
    },
    {
      id: 'behavior-rotation',
      slug: 'behavior-rotation',
      domain: 'social',
      title: '행동 시그널 순환',
      subtitle: '검토된 SNS 집계 항목',
      summary:
        '행동 관련 대화는 꺼지기보다 순환하고 있으며, 새로운 주제가 빠르게 교체되며 피드를 유지하고 있습니다.',
      score: 57,
      classification: '순환 진행',
      change: 1.7,
      updatedAt: isoMinutesAgo(82),
      confidenceBand: 'medium',
      freshnessNote: '시간 단위 리듬의 끝 구간에 가깝습니다.',
      uncertaintyNote: '대화 주제가 순환 중이라 집계 라벨이 실제보다 더 안정적으로 보일 수 있습니다.',
      detailPath: '/sns/behavior-rotation',
      metrics: [
        { label: '검토 출처 수', value: '9' },
        { label: '주제 교체 속도', value: '높음', tone: 'warm' },
        { label: '중복도', value: '낮음', tone: 'cool' },
      ],
      drivers: [
        '새로운 주제가 이전 주제를 빠르게 대체하며 피드 활성을 유지했습니다.',
        '출처 간 중복도가 낮아 전체 확신도는 제한됐습니다.',
        '이 분류는 단일 주제보다는 활동의 연속성을 반영합니다.',
      ],
      cadenceHours: 1,
      sourceCount: 9,
      categories: ['행동', '자금 흐름'],
      sources: ['Reddit', '커뮤니티', '블로그'],
      approvalNote: '승인된 항목만 표시되므로, 조용한 상태는 통과한 항목이 없다는 뜻일 수 있습니다.',
    },
  ];

  return {
    pentagon,
    psychology,
    social,
  };
}
