import type { PentagonSignal, PsychologySignal, SocialSignal } from './types';

function isoMinutesAgo(minutes: number) {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

export function getDemoSignals() {
  const pentagon: PentagonSignal[] = [
    {
      id: 'pizza-index',
      slug: 'pizza-index',
      domain: 'pentagon',
      indexType: 'pizza',
      title: '피자 지수',
      subtitle: '심야 주문 압력',
      summary:
        '모니터링 구역 전반에서 심야 피자 주문이 최근 기준선을 웃돌며, 시간 외 활동이 견조하게 유지되고 있습니다.',
      score: 74,
      classification: '활동 강세',
      change: 6.4,
      updatedAt: isoMinutesAgo(22),
      confidenceBand: 'high',
      freshnessNote: '목표한 시간 단위 갱신 주기 안에서 업데이트됐습니다.',
      uncertaintyNote: '집계 중심 지표라서 지역별 편차가 평균값 안에 가려질 수 있습니다.',
      detailPath: '/pentagon/pizza-index',
      metrics: [
        { label: '기준 대비 주문', value: '+18%', tone: 'warm' },
        { label: '심야 비중', value: '67%', tone: 'warm' },
        { label: '커버리지', value: '12개 구역' },
      ],
      drivers: [
        '주말 주문량이 최근 2주 기준선보다 빠르게 늘었습니다.',
        '심야 수요 비중이 평소보다 높게 반영됐습니다.',
        '특정 한 구역이 아니라 전반적인 확산 형태로 나타났습니다.',
      ],
      cadenceHours: 1,
      sampleSize: 428,
      coverageLabel: '12개 모니터링 구역',
    },
    {
      id: 'gay-bar-index',
      slug: 'gay-bar-index',
      domain: 'pentagon',
      indexType: 'gay-bar',
      title: '바 지수',
      subtitle: '야간 유입 집계',
      summary:
        '유입은 견조하지만 피자 지수만큼 과열되지는 않아, 야간 활동이 안정적으로 이어지는 흐름으로 보입니다.',
      score: 61,
      classification: '안정적 유입',
      change: 2.1,
      updatedAt: isoMinutesAgo(69),
      confidenceBand: 'medium',
      freshnessNote: '시간 단위 갱신 주기 상단에 가까운 시점입니다.',
      uncertaintyNote: '개별 장소 수준 세부 정보는 제외되므로, 작은 지역 급등은 여기서 바로 드러나지 않습니다.',
      detailPath: '/pentagon/gay-bar-index',
      metrics: [
        { label: '기준 대비 유입', value: '+9%', tone: 'warm' },
        { label: '대기 강도', value: '안정', tone: 'neutral' },
        { label: '커버리지', value: '8개 구역' },
      ],
      drivers: [
        '대부분의 모니터링 구역에서 유입이 단기 기준선을 웃돌았습니다.',
        '마감으로 갈수록 대기 압력이 급증하지 않고 안정적으로 유지됐습니다.',
        '특정 한 지역 급등이 아닌 넓은 범위의 흐름으로 나타났습니다.',
      ],
      cadenceHours: 1,
      sampleSize: 193,
      coverageLabel: '8개 모니터링 구역',
    },
  ];

  const psychology: PsychologySignal[] = [
    {
      id: 'us-stock-fear-greed',
      slug: 'us-stock-fear-greed',
      domain: 'psychology',
      indicatorType: 'us-stock-fear-greed',
      title: '미국주식 공탐지수',
      subtitle: '미국 증시 심리 종합',
      summary:
        '미국 증시는 위험 선호가 다시 살아나며 공포 구간을 벗어났지만, 아직 극단적 탐욕까지는 아닌 회복 흐름에 가깝습니다.',
      score: 63,
      classification: '탐욕 회복',
      change: 7.2,
      updatedAt: isoMinutesAgo(18),
      confidenceBand: 'high',
      freshnessNote: '가장 최근 시간 단위 배치 안에서 갱신됐습니다.',
      uncertaintyNote: '종합 지표 특성상 상충하는 세부 신호가 완만하게 보일 수 있습니다.',
      detailPath: '/psychology/us-stock-fear-greed',
      metrics: [
        { label: '변동성 톤', value: '완화', tone: 'cool' },
        { label: '상승 종목 비율', value: '개선', tone: 'warm' },
        { label: '옵션 심리', value: '긍정', tone: 'warm' },
      ],
      drivers: [
        '변동성 민감 지표가 직전 구간보다 완화됐습니다.',
        '상승 종목 비율이 넓어지며 종합 심리를 지지했습니다.',
        '옵션 시장의 위험 선호가 과열 전 단계의 긍정 구간으로 기울었습니다.',
      ],
      cadenceHours: 1,
    },
    {
      id: 'crypto-fear-greed',
      slug: 'crypto-fear-greed',
      domain: 'psychology',
      indicatorType: 'crypto-fear-greed',
      title: '코인 공탐지수',
      subtitle: '가상자산 심리 종합',
      summary:
        '코인 시장은 단기 반등 기대가 살아나며 탐욕 쪽으로 기울고 있지만, 레버리지 과열까지 번진 상황은 아닙니다.',
      score: 58,
      classification: '낙관 우세',
      change: 3.6,
      updatedAt: isoMinutesAgo(54),
      confidenceBand: 'medium',
      freshnessNote: '목표 갱신 구간 안에 있습니다.',
      uncertaintyNote: '가상자산 시장은 변동성이 커서 심리 지표가 짧은 시간 안에 급변할 수 있습니다.',
      detailPath: '/psychology/crypto-fear-greed',
      metrics: [
        { label: '비트코인 톤', value: '강세', tone: 'warm' },
        { label: '알트 심리', value: '회복', tone: 'warm' },
        { label: '과열 경고', value: '보통', tone: 'neutral' },
      ],
      drivers: [
        '비트코인 중심의 낙관 심리가 시장 전반으로 번지고 있습니다.',
        '알트코인 참여가 회복되며 위험 선호를 밀어 올렸습니다.',
        '다만 단기 과열을 경고하는 레버리지 신호도 일부 남아 있습니다.',
      ],
      cadenceHours: 1,
    },
    {
      id: 'kr-stock-fear-greed',
      slug: 'kr-stock-fear-greed',
      domain: 'psychology',
      indicatorType: 'kr-stock-fear-greed',
      title: '한국주식 공탐지수',
      subtitle: '국내 증시 심리 종합',
      summary:
        '국내 증시는 반등 기대와 경계 심리가 맞서며 관망 쪽이 조금 더 우세한 혼조 구간에 머무르고 있습니다.',
      score: 41,
      classification: '관망 우세',
      change: -2.7,
      updatedAt: isoMinutesAgo(101),
      confidenceBand: 'limited',
      freshnessNote: '일반적인 시간 단위 갱신보다 오래된 값입니다.',
      uncertaintyNote: '국내 증시는 수급 이벤트에 따라 심리 온도가 빠르게 뒤집힐 수 있습니다.',
      detailPath: '/psychology/kr-stock-fear-greed',
      metrics: [
        { label: '개인 심리', value: '신중', tone: 'cool' },
        { label: '수급 강도', value: '혼조', tone: 'neutral' },
        { label: '테마 확산', value: '제한적', tone: 'cool' },
      ],
      drivers: [
        '개인 투자자 심리가 적극 매수보다 관망 쪽에 조금 더 기울었습니다.',
        '수급이 한 방향으로 강하게 쏠리지 않아 혼조 흐름이 이어졌습니다.',
        '주도 테마 확산이 제한적이라 탐욕 구간 진입을 막고 있습니다.',
      ],
      cadenceHours: 1,
    },
  ];

  const social: SocialSignal[] = [
    {
      id: 'trump',
      slug: 'trump',
      domain: 'social',
      title: '트럼프',
      subtitle: '검토된 SNS 대화 흐름',
      summary:
        '트럼프 관련 언급량이 다시 빠르게 늘며 시장 해석과 정책 기대를 둘러싼 대화가 강하게 확산되고 있습니다.',
      score: 72,
      classification: '언급 급증',
      change: 6.1,
      updatedAt: isoMinutesAgo(15),
      confidenceBand: 'high',
      freshnessNote: '가장 최근 검토 구간에서 공개됐습니다.',
      uncertaintyNote: '정치 이벤트성 발언 하나로도 대화량이 크게 튈 수 있어 출처 구성이 중요합니다.',
      detailPath: '/sns/trump',
      metrics: [
        { label: '검토 출처 수', value: '14', tone: 'warm' },
        { label: '언급 증가율', value: '+27%', tone: 'warm' },
        { label: '확산 범위', value: '넓음' },
      ],
      drivers: [
        '정책 발언과 인터뷰 클립이 동시에 확산되며 언급량을 끌어올렸습니다.',
        '단일 채널 급등이 아니라 여러 채널에 걸쳐 넓게 분산됐습니다.',
        '후속 댓글 흐름도 초기 이슈를 약화시키기보다 강화하는 쪽이었습니다.',
      ],
      cadenceHours: 1,
      sourceCount: 14,
      categories: ['트럼프'],
      sources: ['X', 'Reddit', '뉴스 댓글'],
      approvalNote: '검토를 통과한 트럼프 관련 대화만 사용자용 피드에 노출됩니다.',
    },
    {
      id: 'elon',
      slug: 'elon',
      domain: 'social',
      title: '일론',
      subtitle: '검토된 SNS 대화 흐름',
      summary:
        '일론 관련 대화는 신제품, 발언, 밈이 함께 섞이며 높은 반응을 유지하고 있지만 방향성은 한쪽으로 고정되지 않았습니다.',
      score: 61,
      classification: '반응 확대',
      change: 4.2,
      updatedAt: isoMinutesAgo(43),
      confidenceBand: 'medium',
      freshnessNote: '최근 1시간 안에 갱신됐습니다.',
      uncertaintyNote: '새로운 발언이나 게시물 하나로도 반응 방향이 급히 뒤집힐 수 있습니다.',
      detailPath: '/sns/elon',
      metrics: [
        { label: '검토 출처 수', value: '12' },
        { label: '반응 증가율', value: '+18%', tone: 'warm' },
        { label: '밈 확산', value: '강함', tone: 'warm' },
      ],
      drivers: [
        'X와 커뮤니티에서 관련 캡처와 해석 게시물이 빠르게 확산됐습니다.',
        '밈형 반응과 진지한 해석이 동시에 붙으며 노출 시간이 길어졌습니다.',
        '다만 대화 방향은 호재와 비판이 섞여 있어 단일 톤으로 굳지 않았습니다.',
      ],
      cadenceHours: 1,
      sourceCount: 12,
      categories: ['일론'],
      sources: ['X', '커뮤니티', '유튜브 댓글'],
      approvalNote: '검토를 통과한 일론 관련 대화만 사용자용 피드에 노출됩니다.',
    },
    {
      id: 'kr-stock-community',
      slug: 'kr-stock-community',
      domain: 'social',
      title: '국내 주식 커뮤니티',
      subtitle: '검토된 SNS 대화 흐름',
      summary:
        '국내 주식 커뮤니티에서는 단기 테마주, 수급 해석, 장중 이슈가 빠르게 순환하며 관심이 분산되고 있습니다.',
      score: 54,
      classification: '테마 순환',
      change: 2.4,
      updatedAt: isoMinutesAgo(82),
      confidenceBand: 'medium',
      freshnessNote: '시간 단위 리듬의 끝 구간에 가깝습니다.',
      uncertaintyNote: '테마 순환이 빠른 구간이라 특정 종목 이슈가 갑자기 중심으로 떠오를 수 있습니다.',
      detailPath: '/sns/kr-stock-community',
      metrics: [
        { label: '검토 출처 수', value: '11' },
        { label: '주제 교체 속도', value: '높음', tone: 'warm' },
        { label: '실시간 반응', value: '활발', tone: 'warm' },
      ],
      drivers: [
        '장중 이슈와 테마주 키워드가 빠르게 교체되며 피드 활성을 유지했습니다.',
        '종목 추천형 글보다 수급과 뉴스 해석형 글 비중이 높았습니다.',
        '실시간 반응이 빠르지만 주제 유지 시간은 길지 않았습니다.',
      ],
      cadenceHours: 1,
      sourceCount: 11,
      categories: ['국내 주식 커뮤니티'],
      sources: ['국내 커뮤니티', '오픈채팅', '블로그'],
      approvalNote: '검토를 통과한 국내 주식 커뮤니티 대화만 사용자용 피드에 노출됩니다.',
    },
    {
      id: 'global-stock-community',
      slug: 'global-stock-community',
      domain: 'social',
      title: '해외주식 커뮤니티',
      subtitle: '검토된 SNS 대화 흐름',
      summary:
        '해외주식 커뮤니티에서는 대형 기술주와 거시 변수 해석이 엇갈리며, 강한 확신보다는 의견 혼조가 두드러지는 구간입니다.',
      score: 46,
      classification: '의견 혼조',
      change: -1.1,
      updatedAt: isoMinutesAgo(97),
      confidenceBand: 'medium',
      freshnessNote: '최근 검토 구간 안에 있습니다.',
      uncertaintyNote: '해외 헤드라인 하나로 커뮤니티 톤이 빠르게 재정렬될 수 있습니다.',
      detailPath: '/sns/global-stock-community',
      metrics: [
        { label: '검토 출처 수', value: '13' },
        { label: '강세 의견', value: '혼조', tone: 'neutral' },
        { label: '거시 반응', value: '민감', tone: 'cool' },
      ],
      drivers: [
        '대형 기술주 해석이 엇갈리며 한쪽 방향으로 쏠리지 않았습니다.',
        '금리와 환율 관련 거시 대화가 종목 논의를 자주 끊었습니다.',
        '커뮤니티별 온도차가 커서 단일 톤으로 요약하기 어려운 흐름입니다.',
      ],
      cadenceHours: 1,
      sourceCount: 13,
      categories: ['해외주식 커뮤니티'],
      sources: ['Reddit', 'Stocktwits', '디스코드'],
      approvalNote: '검토를 통과한 해외주식 커뮤니티 대화만 사용자용 피드에 노출됩니다.',
    },
  ];

  return {
    pentagon,
    psychology,
    social,
  };
}
