import type {
  CollectionJobRecord,
  DashboardSnapshot,
  FeedLayoutItemRecord,
  ProviderRecord,
  ReviewQueueItem,
  RunSummary,
} from '@indicator/shared';

export const demoProviders: ProviderRecord[] = [
  {
    id: 'provider-pizzint',
    code: 'pizzint',
    displayName: 'PizzINT',
    providerKind: 'indicator',
    authState: 'valid',
    legalMode: 'licensed_api',
    sourceHealth: 'healthy',
    freshnessSlaMinutes: 90,
    isEnabled: true,
    config: { supports: ['pizza_index', 'gay_bar_index'] },
    lastSuccessAt: '2026-04-22T09:58:00.000Z',
    lastFailureAt: null,
  },
  {
    id: 'provider-cnn',
    code: 'cnn',
    displayName: 'CNN',
    providerKind: 'sentiment',
    authState: 'not_required',
    legalMode: 'public_web',
    sourceHealth: 'healthy',
    freshnessSlaMinutes: 120,
    isEnabled: true,
    config: { supports: ['fear_greed_index'] },
    lastSuccessAt: '2026-04-22T09:52:00.000Z',
    lastFailureAt: null,
  },
  {
    id: 'provider-cmc',
    code: 'cmc',
    displayName: 'CMC',
    providerKind: 'sentiment',
    authState: 'valid',
    legalMode: 'licensed_api',
    sourceHealth: 'healthy',
    freshnessSlaMinutes: 60,
    isEnabled: true,
    config: { supports: ['market_breadth'] },
    lastSuccessAt: '2026-04-22T09:45:00.000Z',
    lastFailureAt: '2026-04-22T08:02:00.000Z',
  },
  {
    id: 'provider-x',
    code: 'x',
    displayName: 'X',
    providerKind: 'social',
    authState: 'valid',
    legalMode: 'restricted',
    sourceHealth: 'degraded',
    freshnessSlaMinutes: 60,
    isEnabled: true,
    config: { supports: ['sns_rollups'] },
    lastSuccessAt: '2026-04-22T09:10:00.000Z',
    lastFailureAt: '2026-04-22T09:31:00.000Z',
  },
];

export const demoJobs: CollectionJobRecord[] = [
  {
    id: 'job-pizza',
    slug: 'collect-pizzint-pizza-index',
    displayName: 'Collect Pizza Index',
    providerId: 'provider-pizzint',
    parserVersion: 'pizzint-v1',
    scheduleCron: '0 * * * *',
    isEnabled: true,
    publishBehavior: 'review_gated',
    lastRunStatus: 'published',
    lastStartedAt: '2026-04-22T10:00:00.000Z',
    lastFinishedAt: '2026-04-22T10:01:10.000Z',
  },
  {
    id: 'job-gaybar',
    slug: 'collect-pizzint-gay-bar-index',
    displayName: 'Collect Gay Bar Index',
    providerId: 'provider-pizzint',
    parserVersion: 'pizzint-v1',
    scheduleCron: '5 * * * *',
    isEnabled: true,
    publishBehavior: 'review_gated',
    lastRunStatus: 'review_required',
    lastStartedAt: '2026-04-22T09:05:00.000Z',
    lastFinishedAt: '2026-04-22T09:06:08.000Z',
  },
  {
    id: 'job-feargreed',
    slug: 'collect-cnn-fear-greed',
    displayName: 'Collect Fear and Greed',
    providerId: 'provider-cnn',
    parserVersion: 'cnn-fg-v2',
    scheduleCron: '10 * * * *',
    isEnabled: true,
    publishBehavior: 'review_gated',
    lastRunStatus: 'published',
    lastStartedAt: '2026-04-22T09:10:00.000Z',
    lastFinishedAt: '2026-04-22T09:11:03.000Z',
  },
  {
    id: 'job-social',
    slug: 'collect-x-sns-rollup',
    displayName: 'Collect SNS Rollup Candidates',
    providerId: 'provider-x',
    parserVersion: 'x-rollup-v1',
    scheduleCron: '20 * * * *',
    isEnabled: true,
    publishBehavior: 'review_gated',
    lastRunStatus: 'failed',
    lastStartedAt: '2026-04-22T09:20:00.000Z',
    lastFinishedAt: '2026-04-22T09:21:47.000Z',
  },
];

export const demoRuns: RunSummary[] = [
  {
    id: 'run-1000',
    jobId: 'job-pizza',
    jobSlug: 'collect-pizzint-pizza-index',
    providerCode: 'pizzint',
    trigger: 'scheduled',
    status: 'published',
    startedAt: '2026-04-22T10:00:00.000Z',
    finishedAt: '2026-04-22T10:01:10.000Z',
    suspiciousCount: 0,
    errorCode: null,
    errorMessage: null,
    freshnessViolation: false,
    idempotencyKey: 'scheduled-pizza-20260422-1000',
  },
  {
    id: 'run-0905',
    jobId: 'job-gaybar',
    jobSlug: 'collect-pizzint-gay-bar-index',
    providerCode: 'pizzint',
    trigger: 'scheduled',
    status: 'review_required',
    startedAt: '2026-04-22T09:05:00.000Z',
    finishedAt: '2026-04-22T09:06:08.000Z',
    suspiciousCount: 1,
    errorCode: null,
    errorMessage: null,
    freshnessViolation: false,
    idempotencyKey: 'scheduled-gaybar-20260422-0905',
  },
  {
    id: 'run-0920',
    jobId: 'job-social',
    jobSlug: 'collect-x-sns-rollup',
    providerCode: 'x',
    trigger: 'scheduled',
    status: 'failed',
    startedAt: '2026-04-22T09:20:00.000Z',
    finishedAt: '2026-04-22T09:21:47.000Z',
    suspiciousCount: 0,
    errorCode: 'HTTP_429',
    errorMessage: 'Provider rate limit exceeded.',
    freshnessViolation: true,
    idempotencyKey: 'scheduled-social-20260422-0920',
  },
];

export const demoDashboard: DashboardSnapshot = {
  recentRuns: demoRuns,
  failureRateLast24h: 0.17,
  freshnessViolations: 2,
  providerHealth: [
    {
      providerCode: 'pizzint',
      sourceHealth: 'healthy',
      stale: false,
      minutesSinceSuccess: 2,
    },
    {
      providerCode: 'cnn',
      sourceHealth: 'healthy',
      stale: false,
      minutesSinceSuccess: 8,
    },
    {
      providerCode: 'cmc',
      sourceHealth: 'healthy',
      stale: false,
      minutesSinceSuccess: 15,
    },
    {
      providerCode: 'x',
      sourceHealth: 'degraded',
      stale: true,
      minutesSinceSuccess: 50,
    },
  ],
};

export const demoReviewQueue: ReviewQueueItem[] = [
  {
    id: 'review-gaybar',
    runId: 'run-0905',
    entityType: 'indicator_point',
    status: 'pending',
    priority: 1,
    reasonCode: 'VALUE_SPIKE',
    reasonDetail: 'Gay Bar Index moved +28 points in one hour.',
    originalPayload: {
      indicatorKey: 'gay_bar_index',
      valueNumeric: 77.4,
      priorValue: 49.2,
    },
    editedPayload: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: 'review-sns-1',
    runId: 'run-0920',
    entityType: 'sns_rollup',
    status: 'pending',
    priority: 0,
    reasonCode: 'SNS_APPROVAL_REQUIRED',
    reasonDetail: 'All social rollups require operator approval before publish.',
    originalPayload: {
      headline: 'Crypto sentiment rebounded after inflation print',
      sources: ['x-post-1', 'x-post-2'],
    },
    editedPayload: null,
    reviewedBy: null,
    reviewedAt: null,
  },
];

export const demoFeedLayout: FeedLayoutItemRecord[] = [
  {
    id: 'layout-home-penta',
    tabSlug: 'home',
    itemKey: 'home:pentagon-highlight',
    itemKind: 'indicator_card',
    sourceRef: 'pizza_index',
    title: 'Pentagon Highlight',
    subtitle: 'Latest novelty signal',
    body: 'Curated highlight from the Pentagon tab.',
    orderIndex: 10,
    isVisible: true,
    config: { sourceTab: 'pentagon' },
  },
  {
    id: 'layout-pizza',
    tabSlug: 'pentagon',
    itemKey: 'pentagon:pizza-index',
    itemKind: 'indicator_card',
    sourceRef: 'pizza_index',
    title: 'Pizza Index',
    subtitle: 'Crowd signal',
    body: 'Tracks pizza-price and culture-linked shifts.',
    orderIndex: 10,
    isVisible: true,
    config: { format: 'score' },
  },
  {
    id: 'layout-gaybar',
    tabSlug: 'pentagon',
    itemKey: 'pentagon:gay-bar-index',
    itemKind: 'indicator_card',
    sourceRef: 'gay_bar_index',
    title: 'Gay Bar Index',
    subtitle: 'Lifestyle signal',
    body: 'Tracks nightlife-linked indicator movement.',
    orderIndex: 20,
    isVisible: true,
    config: { format: 'score' },
  },
  {
    id: 'layout-feargreed',
    tabSlug: 'psychology',
    itemKey: 'psychology:fear-greed',
    itemKind: 'indicator_card',
    sourceRef: 'fear_greed_index',
    title: 'Fear & Greed',
    subtitle: 'Sentiment composite',
    body: 'Fear-and-greed style market emotion index.',
    orderIndex: 10,
    isVisible: true,
    config: { format: 'gauge' },
  },
  {
    id: 'layout-sns',
    tabSlug: 'sns_feed',
    itemKey: 'sns:top-rollup',
    itemKind: 'sns_rollup',
    sourceRef: 'sns_feed_rollup',
    title: 'Top Rollup',
    subtitle: 'Approved by operations',
    body: 'Latest approved social rollup for publication.',
    orderIndex: 10,
    isVisible: true,
    config: { reviewRequired: true },
  },
];
