import type {
  CollectionJobRecord,
  DashboardSnapshot,
  FeedLayoutItemRecord,
  ProviderRecord,
  ReviewQueueItem,
  RunSummary,
  SnsAdminItemRecord,
} from './shared-types';

export const demoProviders: ProviderRecord[] = [
  {
    id: 'provider-pizzint',
    code: 'pizzint',
    displayName: 'PizzINT',
    providerKind: 'indicator',
    authState: 'valid',
    legalMode: 'licensed_api',
    sourceHealth: 'healthy',
    freshnessSlaMinutes: 90,
    isEnabled: true,
    config: { supports: ['pizza_index', 'gay_bar_index'] },
    lastSuccessAt: '2026-04-22T09:58:00.000Z',
    lastFailureAt: null,
  },
  {
    id: 'provider-cnn',
    code: 'cnn',
    displayName: 'CNN',
    providerKind: 'sentiment',
    authState: 'not_required',
    legalMode: 'public_web',
    sourceHealth: 'healthy',
    freshnessSlaMinutes: 120,
    isEnabled: true,
    config: { supports: ['fear_greed_index'] },
    lastSuccessAt: '2026-04-22T09:52:00.000Z',
    lastFailureAt: null,
  },
  {
    id: 'provider-cmc',
    code: 'cmc',
    displayName: 'CMC',
    providerKind: 'sentiment',
    authState: 'valid',
    legalMode: 'licensed_api',
    sourceHealth: 'healthy',
    freshnessSlaMinutes: 60,
    isEnabled: true,
    config: { supports: ['market_breadth'] },
    lastSuccessAt: '2026-04-22T09:45:00.000Z',
    lastFailureAt: '2026-04-22T08:02:00.000Z',
  },
  {
    id: 'provider-x',
    code: 'x',
    displayName: 'X',
    providerKind: 'social',
    authState: 'valid',
    legalMode: 'restricted',
    sourceHealth: 'degraded',
    freshnessSlaMinutes: 60,
    isEnabled: true,
    config: { supports: ['sns_rollups'] },
    lastSuccessAt: '2026-04-22T09:10:00.000Z',
    lastFailureAt: '2026-04-22T09:31:00.000Z',
  },
];

export const demoJobs: CollectionJobRecord[] = [
  {
    id: 'job-pizza',
    slug: 'collect-pizzint-pizza-index',
    displayName: '피자 지수 수집',
    providerId: 'provider-pizzint',
    parserVersion: 'pizzint-v1',
    scheduleCron: '0 * * * *',
    isEnabled: true,
    publishBehavior: 'review_gated',
    lastRunStatus: 'published',
    lastStartedAt: '2026-04-22T10:00:00.000Z',
    lastFinishedAt: '2026-04-22T10:01:10.000Z',
  },
  {
    id: 'job-gaybar',
    slug: 'collect-pizzint-gay-bar-index',
    displayName: '바 지수 수집',
    providerId: 'provider-pizzint',
    parserVersion: 'pizzint-v1',
    scheduleCron: '5 * * * *',
    isEnabled: true,
    publishBehavior: 'review_gated',
    lastRunStatus: 'review_required',
    lastStartedAt: '2026-04-22T09:05:00.000Z',
    lastFinishedAt: '2026-04-22T09:06:08.000Z',
  },
  {
    id: 'job-feargreed',
    slug: 'collect-cnn-fear-greed',
    displayName: '공포탐욕 지수 수집',
    providerId: 'provider-cnn',
    parserVersion: 'cnn-fg-v2',
    scheduleCron: '10 * * * *',
    isEnabled: true,
    publishBehavior: 'review_gated',
    lastRunStatus: 'published',
    lastStartedAt: '2026-04-22T09:10:00.000Z',
    lastFinishedAt: '2026-04-22T09:11:03.000Z',
  },
  {
    id: 'job-social',
    slug: 'collect-x-sns-rollup',
    displayName: 'SNS 후보 수집',
    providerId: 'provider-x',
    parserVersion: 'x-rollup-v1',
    scheduleCron: '20 * * * *',
    isEnabled: true,
    publishBehavior: 'review_gated',
    lastRunStatus: 'failed',
    lastStartedAt: '2026-04-22T09:20:00.000Z',
    lastFinishedAt: '2026-04-22T09:21:47.000Z',
  },
];

export const demoRuns: RunSummary[] = [
  {
    id: 'run-1000',
    jobId: 'job-pizza',
    jobSlug: 'collect-pizzint-pizza-index',
    providerCode: 'pizzint',
    trigger: 'scheduled',
    status: 'published',
    startedAt: '2026-04-22T10:00:00.000Z',
    finishedAt: '2026-04-22T10:01:10.000Z',
    suspiciousCount: 0,
    errorCode: null,
    errorMessage: null,
    freshnessViolation: false,
    idempotencyKey: 'scheduled-pizza-20260422-1000',
  },
  {
    id: 'run-0905',
    jobId: 'job-gaybar',
    jobSlug: 'collect-pizzint-gay-bar-index',
    providerCode: 'pizzint',
    trigger: 'scheduled',
    status: 'review_required',
    startedAt: '2026-04-22T09:05:00.000Z',
    finishedAt: '2026-04-22T09:06:08.000Z',
    suspiciousCount: 1,
    errorCode: null,
    errorMessage: null,
    freshnessViolation: false,
    idempotencyKey: 'scheduled-gaybar-20260422-0905',
  },
  {
    id: 'run-0920',
    jobId: 'job-social',
    jobSlug: 'collect-x-sns-rollup',
    providerCode: 'x',
    trigger: 'scheduled',
    status: 'failed',
    startedAt: '2026-04-22T09:20:00.000Z',
    finishedAt: '2026-04-22T09:21:47.000Z',
    suspiciousCount: 0,
    errorCode: 'HTTP_429',
    errorMessage: '소스 호출 제한을 초과했습니다.',
    freshnessViolation: true,
    idempotencyKey: 'scheduled-social-20260422-0920',
  },
];

export const demoDashboard: DashboardSnapshot = {
  recentRuns: demoRuns,
  failureRateLast24h: 0.17,
  freshnessViolations: 2,
  providerHealth: [
    {
      providerCode: 'pizzint',
      sourceHealth: 'healthy',
      stale: false,
      minutesSinceSuccess: 2,
    },
    {
      providerCode: 'cnn',
      sourceHealth: 'healthy',
      stale: false,
      minutesSinceSuccess: 8,
    },
    {
      providerCode: 'cmc',
      sourceHealth: 'healthy',
      stale: false,
      minutesSinceSuccess: 15,
    },
    {
      providerCode: 'x',
      sourceHealth: 'degraded',
      stale: true,
      minutesSinceSuccess: 50,
    },
  ],
};

export const demoReviewQueue: ReviewQueueItem[] = [
  {
    id: 'review-gaybar',
    runId: 'run-0905',
    entityType: 'indicator_point',
    status: 'pending',
    priority: 1,
    reasonCode: 'VALUE_SPIKE',
    reasonDetail: '바 지수가 한 시간 만에 28포인트 상승했습니다.',
    originalPayload: {
      indicatorKey: 'gay_bar_index',
      valueNumeric: 77.4,
      priorValue: 49.2,
    },
    editedPayload: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: 'review-sns-1',
    runId: 'run-0920',
    entityType: 'sns_rollup',
    status: 'pending',
    priority: 0,
    reasonCode: 'SNS_APPROVAL_REQUIRED',
    reasonDetail: '모든 SNS 요약은 게시 전에 운영자 승인이 필요합니다.',
    originalPayload: {
      headline: '물가 발표 이후 가상자산 심리가 다시 살아났습니다.',
      sources: ['x-post-1', 'x-post-2'],
    },
    editedPayload: null,
    reviewedBy: null,
    reviewedAt: null,
  },
];

export const demoSnsControlItems: SnsAdminItemRecord[] = [
  {
    layoutId: 'layout-sns-trump',
    tabSlug: 'sns_feed',
    itemKey: 'sns:trump',
    itemKind: 'sns_rollup',
    sourceRef: 'sns_trump_rollup',
    title: '트럼프',
    subtitle: '정치 이벤트 반응',
    body: '트럼프 관련 대화 흐름을 운영에서 직접 정리합니다.',
    orderIndex: 10,
    isVisible: true,
    config: { reviewRequired: true, editorOwned: true },
    currentContent: {
      title: '트럼프',
      subtitle: '정치 이벤트 반응',
      summary: '정책 발언과 선거 관련 해석이 동시에 붙으며 대화량이 빠르게 확대되고 있습니다.',
      score: 72,
      classification: '언급 급증',
      change: 6.1,
      metrics: [
        { label: '언급 증가율', value: '+27%', tone: 'warm' },
        { label: '확산 범위', value: '넓음', tone: 'warm' },
        { label: '변동성', value: '높음', tone: 'neutral' },
      ],
      drivers: [
        '정책 발언과 인터뷰 클립이 여러 채널에서 동시에 확산되고 있습니다.',
        '뉴스 댓글과 커뮤니티 해석글이 서로 재인용되며 체류 시간을 늘리고 있습니다.',
      ],
      categories: ['트럼프'],
      sourceItems: ['X', 'Reddit', '뉴스 댓글'],
      approvalNote: '검토를 통과한 트럼프 관련 대화만 사용자용 피드에 노출됩니다.',
    },
    publishedAt: '2026-04-22T10:15:00.000Z',
    sourceRunId: 'run-0920',
    hasPublishedState: true,
  },
  {
    layoutId: 'layout-sns-elon',
    tabSlug: 'sns_feed',
    itemKey: 'sns:elon',
    itemKind: 'sns_rollup',
    sourceRef: 'sns_elon_rollup',
    title: '일론',
    subtitle: '인물 발언 반응',
    body: '일론 관련 대화와 밈 흐름을 운영에서 직접 조절합니다.',
    orderIndex: 20,
    isVisible: true,
    config: { reviewRequired: true, editorOwned: true },
    currentContent: {
      title: '일론',
      subtitle: '인물 발언 반응',
      summary: '신제품, 발언, 밈이 한꺼번에 묶이며 강한 반응이 유지되고 있지만 방향성은 한쪽으로 고정되지 않았습니다.',
      score: 61,
      classification: '반응 확대',
      change: 4.2,
      metrics: [
        { label: '반응 증가율', value: '+18%', tone: 'warm' },
        { label: '밈 확산', value: '강함', tone: 'warm' },
        { label: '해석 일치도', value: '낮음', tone: 'cool' },
      ],
      drivers: [
        'X와 커뮤니티에서 관련 캡처와 해석 게시물이 빠르게 확산됐습니다.',
        '호재와 비판이 섞여 있어 단일 톤으로 굳지 않은 상태입니다.',
      ],
      categories: ['일론'],
      sourceItems: ['X', '커뮤니티', '유튜브 댓글'],
      approvalNote: '검토를 통과한 일론 관련 대화만 사용자용 피드에 노출됩니다.',
    },
    publishedAt: '2026-04-22T10:03:00.000Z',
    sourceRunId: 'run-0920',
    hasPublishedState: true,
  },
  {
    layoutId: 'layout-sns-kr-community',
    tabSlug: 'sns_feed',
    itemKey: 'sns:kr-stock-community',
    itemKind: 'sns_rollup',
    sourceRef: 'sns_kr_stock_community_rollup',
    title: '국내 주식 커뮤니티',
    subtitle: '테마주/수급 대화',
    body: '국내 주식 커뮤니티 흐름을 운영에서 직접 정리합니다.',
    orderIndex: 30,
    isVisible: true,
    config: { reviewRequired: true, editorOwned: true },
    currentContent: {
      title: '국내 주식 커뮤니티',
      subtitle: '테마주/수급 대화',
      summary: '장중 이슈와 테마주 키워드가 빠르게 교체되며 실시간 반응은 활발하지만, 한 주제가 오래 유지되지는 않습니다.',
      score: 54,
      classification: '테마 순환',
      change: 2.4,
      metrics: [
        { label: '주제 교체 속도', value: '높음', tone: 'warm' },
        { label: '실시간 반응', value: '활발', tone: 'warm' },
        { label: '지속성', value: '짧음', tone: 'neutral' },
      ],
      drivers: [
        '종목 추천형 글보다 수급과 뉴스 해석형 글 비중이 높았습니다.',
        '장중 이슈가 빠르게 바뀌어 피드의 중심 주제가 계속 교체됐습니다.',
      ],
      categories: ['국내 주식 커뮤니티'],
      sourceItems: ['국내 커뮤니티', '오픈채팅', '블로그'],
      approvalNote: '검토를 통과한 국내 주식 커뮤니티 대화만 사용자용 피드에 노출됩니다.',
    },
    publishedAt: '2026-04-22T09:42:00.000Z',
    sourceRunId: 'run-0920',
    hasPublishedState: true,
  },
  {
    layoutId: 'layout-sns-global-community',
    tabSlug: 'sns_feed',
    itemKey: 'sns:global-stock-community',
    itemKind: 'sns_rollup',
    sourceRef: 'sns_global_stock_community_rollup',
    title: '해외주식 커뮤니티',
    subtitle: '미국장/거시 해석',
    body: '해외주식 커뮤니티 흐름을 운영에서 직접 정리합니다.',
    orderIndex: 40,
    isVisible: true,
    config: { reviewRequired: true, editorOwned: true },
    currentContent: {
      title: '해외주식 커뮤니티',
      subtitle: '미국장/거시 해석',
      summary: '대형 기술주와 거시 변수 해석이 엇갈리며 강한 확신보다는 의견 혼조가 두드러지는 구간입니다.',
      score: 46,
      classification: '의견 혼조',
      change: -1.1,
      metrics: [
        { label: '강세 의견', value: '혼조', tone: 'neutral' },
        { label: '거시 반응', value: '민감', tone: 'cool' },
        { label: '커뮤니티 편차', value: '큼', tone: 'cool' },
      ],
      drivers: [
        '대형 기술주 해석이 엇갈리며 한쪽 방향으로 쏠리지 않았습니다.',
        '금리와 환율 관련 거시 대화가 종목 논의를 자주 끊었습니다.',
      ],
      categories: ['해외주식 커뮤니티'],
      sourceItems: ['Reddit', 'Stocktwits', '디스코드'],
      approvalNote: '검토를 통과한 해외주식 커뮤니티 대화만 사용자용 피드에 노출됩니다.',
    },
    publishedAt: '2026-04-22T09:26:00.000Z',
    sourceRunId: 'run-0920',
    hasPublishedState: true,
  },
];

export const demoFeedLayout: FeedLayoutItemRecord[] = [
  {
    id: 'layout-home-penta',
    tabSlug: 'home',
    itemKey: 'home:pentagon-highlight',
    itemKind: 'indicator_card',
    sourceRef: 'pizza_index',
    title: '펜타곤 하이라이트',
    subtitle: '최신 보조 지표',
    body: '펜타곤 탭에서 선별한 대표 지표입니다.',
    orderIndex: 10,
    isVisible: true,
    config: { sourceTab: 'pentagon' },
  },
  {
    id: 'layout-pizza',
    tabSlug: 'pentagon',
    itemKey: 'pentagon:pizza-index',
    itemKind: 'indicator_card',
    sourceRef: 'pizza_index',
    title: '피자 지수',
    subtitle: '대중 흐름 지표',
    body: '피자 관련 움직임과 문화 신호 변화를 추적합니다.',
    orderIndex: 10,
    isVisible: true,
    config: { format: 'score' },
  },
  {
    id: 'layout-gaybar',
    tabSlug: 'pentagon',
    itemKey: 'pentagon:gay-bar-index',
    itemKind: 'indicator_card',
    sourceRef: 'gay_bar_index',
    title: '바 지수',
    subtitle: '생활 흐름 지표',
    body: '야간 유입과 생활 패턴 변화를 추적합니다.',
    orderIndex: 20,
    isVisible: true,
    config: { format: 'score' },
  },
  {
    id: 'layout-feargreed',
    tabSlug: 'psychology',
    itemKey: 'psychology:fear-greed',
    itemKind: 'indicator_card',
    sourceRef: 'fear_greed_index',
    title: '공포탐욕 지수',
    subtitle: '심리 종합 지표',
    body: '시장 심리를 공포와 탐욕 기준으로 종합한 지표입니다.',
    orderIndex: 10,
    isVisible: true,
    config: { format: 'gauge' },
  },
  {
    id: 'layout-sns-trump',
    tabSlug: 'sns_feed',
    itemKey: 'sns:trump',
    itemKind: 'sns_rollup',
    sourceRef: 'sns_trump_rollup',
    title: '트럼프',
    subtitle: '정치 이벤트 반응',
    body: '트럼프 관련 대화 흐름을 운영에서 직접 정리합니다.',
    orderIndex: 10,
    isVisible: true,
    config: { reviewRequired: true, editorOwned: true },
  },
  {
    id: 'layout-sns-elon',
    tabSlug: 'sns_feed',
    itemKey: 'sns:elon',
    itemKind: 'sns_rollup',
    sourceRef: 'sns_elon_rollup',
    title: '일론',
    subtitle: '인물 발언 반응',
    body: '일론 관련 대화와 밈 흐름을 운영에서 직접 조절합니다.',
    orderIndex: 20,
    isVisible: true,
    config: { reviewRequired: true, editorOwned: true },
  },
  {
    id: 'layout-sns-kr-community',
    tabSlug: 'sns_feed',
    itemKey: 'sns:kr-stock-community',
    itemKind: 'sns_rollup',
    sourceRef: 'sns_kr_stock_community_rollup',
    title: '국내 주식 커뮤니티',
    subtitle: '테마주/수급 대화',
    body: '국내 주식 커뮤니티 흐름을 운영에서 직접 정리합니다.',
    orderIndex: 30,
    isVisible: true,
    config: { reviewRequired: true, editorOwned: true },
  },
  {
    id: 'layout-sns-global-community',
    tabSlug: 'sns_feed',
    itemKey: 'sns:global-stock-community',
    itemKind: 'sns_rollup',
    sourceRef: 'sns_global_stock_community_rollup',
    title: '해외주식 커뮤니티',
    subtitle: '미국장/거시 해석',
    body: '해외주식 커뮤니티 흐름을 운영에서 직접 정리합니다.',
    orderIndex: 40,
    isVisible: true,
    config: { reviewRequired: true, editorOwned: true },
  },
];
